names:
  0: Limita de viteza 20 km/h
  1: Limita de viteza 80 km/h
  2: Intersectie prioritara
  3: Stop
  4: Acces interzis
  5: Curba periculoasa la dreapta
  6: Drum ingustat
  7: Trecere pentru pietoni
  8: Copii in traversare
  9: Gheata sau zapada
  10: Animale salbatice
  11: Sfarsitul restrictiei de viteza
  12: Obligatie la stanga
  13: Obligatie inainte sau la dreapta
  14: Obligatie inainte sau la stanga
